# Generated by Django 4.0.4 on 2022-05-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagModel',
            new_name='PostTagModel',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
